//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SUARweb
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Agreement
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Agreement()
        {
            this.Payments = new HashSet<Payment>();
        }
    
        public int ID { get; set; }
        [DisplayName("Статус договора")]
        public int StatusId { get; set; }
        [DisplayName("Дата начала")]
        public System.DateTime StartDate { get; set; }
        [DisplayName("Дата окончания")]
        public System.DateTime EndDate { get; set; }
        [DisplayName("Частота платы")]
        public int PayFrequencyId { get; set; }
        [DisplayName("Арендная плата")]
        public decimal PaySum { get; set; }
        [DisplayName("Арендатор")]
        public string RenterId { get; set; }
        [DisplayName("Квартира")]
        public int ApartmentId { get; set; }
    
        public virtual Agreement_Status Agreement_Status { get; set; }
        public virtual Apartment Apartment { get; set; }
        public virtual Client Client { get; set; }
        public virtual Pay_Frequency Pay_Frequency { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payment> Payments { get; set; }
    }
}
