//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SUARweb
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Client
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Client()
        {
            this.Agreements = new HashSet<Agreement>();
            this.Apartments = new HashSet<Apartment>();
        }

        [DisplayName("Паспорт")]
        public string PassportID { get; set; }
        [DisplayName("ФИО")]
        public string Fullname { get; set; }
        [DisplayName("Адрес регистрации")]
        public string RegistrationAddress { get; set; }
        [DisplayName("Дата рождения")]
        public System.DateTime Birthdate { get; set; }
        [DisplayName("Пол")]
        public int GenderId { get; set; }
        [DisplayName("Гражданство")]
        public string Citizenship { get; set; }
        [DisplayName("Код УФМС")]
        public string UFMScode { get; set; }
        [DisplayName("Дата выдачи паспорта")]
        public System.DateTime PassportDate { get; set; }
        [DisplayName("ИНН")]
        public string INN { get; set; }
        [DisplayName("КПП")]
        public string KPP { get; set; }
        [DisplayName("БИК")]
        public string BIK { get; set; }
        [DisplayName("Номер счета")]
        public string BankAccount { get; set; }
        [DisplayName("Телефон")]
        public string Phone { get; set; }
        [DisplayName("Эл. почта")]
        public string Email { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Agreement> Agreements { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Apartment> Apartments { get; set; }
        public virtual Gender Gender { get; set; }


        public string GetPassportAndFullname()
        {
            return PassportID + " " + Fullname;
        }
    }
}
