//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SUARweb
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SuarDbContext : DbContext
    {
        public SuarDbContext()
            : base("name=SuarDbContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Agreement_Status> AgreementStatus { get; set; }
        public virtual DbSet<Agreement> Agreements { get; set; }
        public virtual DbSet<Apartment> Apartments { get; set; }
        public virtual DbSet<Balcony_Type> BalconyType { get; set; }
        public virtual DbSet<Building> Buildings { get; set; }
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<Construction_Type> ConstructionType { get; set; }
        public virtual DbSet<District> Districts { get; set; }
        public virtual DbSet<Gender> Genders { get; set; }
        public virtual DbSet<Heating_Type> HeatingType { get; set; }
        public virtual DbSet<Internet_Conn> InternetConn { get; set; }
        public virtual DbSet<Pay_Frequency> PayFrequency { get; set; }
        public virtual DbSet<Payment> Payments { get; set; }
        public virtual DbSet<Planning_Type> PlanningType { get; set; }
        public virtual DbSet<Rental_Status> RentalStatus { get; set; }
        public virtual DbSet<Settlement_Type> SettlementType { get; set; }
        public virtual DbSet<Settlement> Settlements { get; set; }
        public virtual DbSet<Subject> Subjects { get; set; }
        public virtual DbSet<Television> Televisions { get; set; }
    }
}
