//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SUARweb
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Payment
    {
        public int ID { get; set; }
        [DisplayName("Сумма")]
        public decimal Sum { get; set; }
        [DisplayName("Время")]
        public System.DateTime DateAndTime { get; set; }
        [DisplayName("Договор")]
        public int AgreementId { get; set; }
    
        public virtual Agreement Agreement { get; set; }
    }
}
