//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SUARweb.Models
{
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using SUARweb.Exporters;
    using SUARweb.Models.CustomValidation;

    public partial class Payment : IExportableEntity
    {
        public int ID { get; set; }

        [DisplayName("Сумма")]
        [Required(ErrorMessage = "Это поле обязательно")]
        [PaySum(ErrorMessage = "Неверный формат ввода")]
        public decimal Sum { get; set; }

        [DisplayName("Время")]
        public System.DateTime DateAndTime { get; set; }

        [DisplayName("Договор")]
        public int AgreementId { get; set; }

        public virtual Agreement Agreement { get; set; }


        public Dictionary<string, dynamic> GetExportData()
        {
            return new Dictionary<string, dynamic>()
            {
                { "Код договора", Agreement.ID },
                { "Плательщик", Agreement.Client.GetPassportAndFullname() },
                { "Получатель", Agreement.Apartment.Client.GetPassportAndFullname() },
                { "Сумма", Sum },
                { "Дата и время", DateAndTime },
            };
        }
    }
}
